language: ruby
services: mongodb
rvm:
- 2.3.0
script: bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: avzgAexz+3ccN7i7r8ICj0x4Vs82LN/aUhi8aq7efwys4BYOkFnWVA+XiyIjgb2l+deXfSW6I1qz8KgPZW+P5ojjpiM4G/l9YohbbWFwPfHyL2e02JRkWLrhjc9W/5uvDjraErDZfu9w+oTSrAcqrYwu8U+QJaB2z0815gVnopI19aAS9WBYjBsn//xHy7zc8/AarAvnfLkfDfSkqLoaofaymQyGaC8p03cMX/3muIPQX1ojmfD1a3/0wij8KDZ+fp6X0oNSduwBc/LzPNwYD5xEQXZ7zptE/c691jg9GVYjYtjPYH+kKQXPwOL3QcsTGqg1/IqjtsLTd7dMnBzNObgJBFtoMxvhZx5ipxrXkSGam67xPVHEmSY8+ivBVtkBrhLxzqy9gbwnYZ3PvNMZTofXYF4ra/eZQs/o55Cu1JQz/txQsjURSVtn2wOY88yvb0hPDeJvBqYbkvD+aQEScp1Iq1Tzxythw6XMRc0rfFoXVa9neTPLWtGvBUbsbeMNAaEc+yLxel1DpuhBth37a0bzETiABcJ1VlYBcn+scBNGQtJtb6GULgkn1zJcTI8Vok8fxyWK3YjTIVZSai0+wW/6s8gtdLuTY4z8XYthXIgnQpPUiOjB1PdPqqfctR/vkOrZmruplsYe/uOvzWeLcdiLJKQ1ckO8Bh/uuIip4B8=
  app: muyiwa-real-time-chat
  on:
    repo: muyiwaolu/real-time-chat
