language: ruby
rvm:
- 2.3.0
script: bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: U/x46xIOYtjoSAAd4pQDFmQ6Dcj7Bp3UgQ+4H/AJGB3AkLD6X7BB5tOKoC5kE9kbj6zUo5OuO8616GfwNfxsVYU/m8r8CemJ5BkN5G0jB6sknA+B/2APYJbaz0+qP2q7U58SSFJ7G0li1v3SuaPpps1F3ySbFra5nbreXZI7o2clHjZRoXCVZ9SXmiNN6CzUYSjF/XQpb+mTu/Sd9//hW4tADnJ5BKbawdJ2sqdnFkXMNlDKUM810Hzzi5p47gGUrJsQRSlPpULosiTRjMPsawByLIOBPb8ujA1H0Pg+LXIMkSj0hEjOsV7eOHaZxq4EgB4IzV8UB2MkoRK28Y4hrdAQohhJoAenlmfdbI/IJNAmyGB2ayZuBdH8bIqvRIwT3QDjOq0puiAE7Qp2tx4i7PmK5cnVGx9TVeXOyWLqjD23OuRIMQRumbGfyOM1XL3LgVo4DCzs1PVFEqdAIWAdbG5CbbSOHzzTmsPPxk0QxEgwD3j6odGlteoy1pd31AcipaKdEJyYfFM5RoRDBSU8q9xHiZDgyCXO3BwYleGhlN4G+ukMI3+Yymm95aJdRHxFEZF55cvtAiYgttsr/xTEi80IQ9u3GvjXUm4R8ElmebVN5gnAnJpB0Eht3QgVblFgXyTjdo7MREPZ8W9D3g9YBCNOVx6nhJxsri0HZsvUW8g=
    app: muyiwa-real-time-chat
