development:
  clients:
    default:
      database: real_time_chat_development
      hosts:
        - localhost:27017

  options:
    raise_not_found_error: false 

test:
  clients:
    default:
      database: real_time_chat_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
  options:
    raise_not_found_error: false
production:
  clients:
     default:
       uri: <%= ENV['MONGODB_URI'] %>
       options:
         connect_timeout: 15
  options:
    raise_not_found_error: false
